CREATE TABLE `sudhanshu_php_blog`.`posts`
( `post_id` INT(100) NOT NULL AUTO_INCREMENT ,
`post_tags` VARCHAR(244) NOT NULL ,
`post_comment_count` INT(100) NOT NULL ,
`post_status` VARCHAR(244) NOT NULL ,
PRIMARY KEY (`post_id`)) ENGINE = InnoDB;

ALTER TABLE `posts`
ADD `post_category_id` INT(100) NOT NULL AFTER `post_status`,
ADD `post_title` VARCHAR(244) NOT NULL AFTER `post_category_id`,
ADD `post_author` VARCHAR(244) NOT NULL AFTER `post_title`,
ADD `post_date` DATE NOT NULL AFTER `post_author`,
ADD `post_image` VARCHAR(244) NOT NULL AFTER `post_date`,
ADD `post_content` TEXT NOT NULL AFTER `post_image`,
ADD `post_category` VARCHAR(244) NOT NULL AFTER `post_content`,
ADD `post_link` VARCHAR(244) NOT NULL AFTER `post_category`;


CREATE TABLE `sudhanshu_php_blog`.`admin`
( `ADMIN_ID` INT(100) NOT NULL AUTO_INCREMENT ,
`ADMIN_USERNAME` VARCHAR(244) NOT NULL ,
`ADMIN_PASSWORD` VARCHAR(244) NOT NULL ,
PRIMARY KEY (`ADMIN_ID`)) ENGINE = InnoDB;


CREATE TABLE `sudhanshu_php_blog`.`comments`
( `COMMENT_ID` INT(100) NOT NULL AUTO_INCREMENT ,
`COMMENT_POST_ID` INT(100) NOT NULL ,
`COMMENT_AUTHOR` VARCHAR(244) NOT NULL ,
`COMMENT_EMAIL` VARCHAR(244) NOT NULL ,
PRIMARY KEY (`COMMENT_ID`)) ENGINE = InnoDB;

ALTER TABLE `comments` ADD `COMMENT_CONTENT` TEXT NOT NULL AFTER `COMMENT_EMAIL`,
ADD `COMMENT_STATUS` VARCHAR(244) NOT NULL AFTER `COMMENT_CONTENT`,
ADD `COMMENT_DATE` DATE NOT NULL AFTER `COMMENT_STATUS`,
ADD `COMMENT_POST_TITLE` VARCHAR(244) NOT NULL AFTER `COMMENT_DATE`,
ADD `COMMENT_TAG` VARCHAR(100) NOT NULL AFTER `COMMENT_POST_TITLE`;


CREATE TABLE `sudhanshu_php_blog`.`users`
( `USER_ID` INT(30) NOT NULL AUTO_INCREMENT ,
`USER_NAME` VARCHAR(244) NOT NULL ,
`USER_PASSWORD` VARCHAR(244) NOT NULL ,
`USER_FIRST_NAME` VARCHAR(244) NOT NULL ,
`USER_LAST_NAME` VARCHAR(244) NOT NULL ,
`EMAIL` VARCHAR(244) NOT NULL ,
`USER_IMAGE` TEXT NOT NULL ,
`ROLE` VARCHAR(244) NOT NULL ,
`RAND_SALT` VARCHAR(244) NOT NULL ,
`USER_REGISTERED_DATE` DATE NOT NULL , PRIMARY KEY (`USER_ID`)) ENGINE = InnoDB;
